[[main]]
name = "Posts"
pageRef = "posts"
weight = 1





[[main]]
name = "Projects"
pageRef = "projects"
weight = 2


[[main]]
name = "Resume"
pageRef = "resume"
weight = 3

[[main]]
name = "About"
pageRef = "about"
weight = 4

[[footer]]
none = "none"
